backend:
  name: git-gateway
  branch: main
media_folder: public/img
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: principles
    label: Principles
    folder: content/principles/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: principles
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
  - name: styles
    label: Styles
    folder: content/styles/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: styles
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
          - label: Dos & Don'ts
            name: dosdonts
            widget: list
            required: false
            fields:
              - label: Description
                name: description
                widget: markdown
                required: false
              - label: Do
                name: do
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/styles
              - label: Don't
                name: dont
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/styles
  - name: patterns
    label: Patterns
    folder: content/patterns/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: patterns
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
          - label: Dos & Don'ts
            name: dosdonts
            widget: list
            required: false
            fields:
              - label: Description
                name: description
                widget: markdown
                required: false
              - label: Do
                name: do
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/patterns
              - label: Don't
                name: dont
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/patterns
  - name: components
    label: Components
    folder: content/components/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: components
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
          - label: Dos & Don'ts
            name: dosdonts
            widget: list
            required: false
            fields:
              - label: Description
                name: description
                widget: markdown
                required: false
              - label: Do
                name: do
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/components
              - label: Don't
                name: dont
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/components
  - name: words
    label: Words
    folder: content/words/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: words
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
          - label: Dos & Don'ts
            name: dosdonts
            widget: list
            required: false
            fields:
              - label: Description
                name: description
                widget: markdown
                required: false
              - label: Do
                name: do
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/words
              - label: Don't
                name: dont
                widget: image
                required: false
                allow_multiple: false
                choose_url: false
                media_folder: /public/img/words
  - name: resources
    label: Resources
    folder: content/resources/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: resources
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
  - name: about-atlas
    label: About Atlas
    folder: content/about-atlas/
    create: true
    editor:
      preview: false
    fields:
      - label: Collection Name
        name: collection_name
        widget: hidden
        default: about atlas
      - label: Title
        name: title
        widget: string
      - label: Headline
        name: headline
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: Sections
        name: sections
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Content
            name: content
            widget: markdown
            required: false
